version: '3.6'

services:
  giis.backend:
    image: giis-backend
    build:
      context: ./giis-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MYSQL_USER=stud
      - MYSQL_PASSWORD=stud
      - DB_HOST=db
      - MYSQL_DATABASE=giis
    depends_on:
      - db
    networks:
      - giis-app
    volumes:
      - ./giis-backend:/usr/src/app
  giis.frontend:
    image: giis-frontend
    build:
      context: ./giis-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - giis-app
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
    depends_on:
      - giis.backend
    volumes:
      - ./giis-frontend:/usr/src/app
      - /usr/src/app/node_modules
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: giis
      MYSQL_USER: stud
      MYSQL_PASSWORD: stud
    ports:
      - "3307:3306"
    networks:
      - giis-app
    volumes:
      - db-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: my-secret-pw
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - giis-app
networks:
  giis-app:
    driver: bridge
volumes:
  db-data: